name: Run Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser to run tests (chrome or firefox)"
        required: false
        default: "firefox"

  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest tests 
        run: |
          pytest test_guru99_login.py --browser=${{ github.event.inputs.browser || 'firefox' }} --headless


      - name: Upload Robot Logs (optional)
        uses: actions/upload-artifact@v4
        with:
          name: robot-logs
          path: |
            output.xml
            log.html
            report.html

      - name: Upload Screenshots on Failure (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots
          path: screenshots/
