name: Run Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser to run tests on (chrome or firefox)"
        required: false
        default: "firefox"

  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-robotframework  # Ensure Robot plugin is installed

      - name: Run Pytest tests (headless)
        run: |
          pytest test_guru99_login.py --browser=${{ github.event.inputs.browser || 'firefox' }} --headless

      - name: Run Robot Framework tests
        run: |
          pytest Demo-Bao.robot \
            --robotframework-output=output.xml \
            --robotframework-log=log.html \
            --robotframework-report=report.html

      - name: Upload Robot Logs
        uses: actions/upload-artifact@v4
        with:
          name: robot-logs
          path: |
            output.xml
            log.html
            report.html

      - name: Upload Screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots
          path: |
            screenshots/
